os:
  - linux
services:
  - docker
language: node_js
node_js:
  - "8.9.4"
jdk:
  - oraclejdk8
sudo: false
addons:
    apt:
        packages:
            - sshpass
cache:
  directories:
    - node
    - node_modules
    - $HOME/.m2
    - $HOME/.yarn-cache
env:
  global:
    - NODE_VERSION=8.9.4
    - SPRING_OUTPUT_ANSI_ENABLED=ALWAYS
    - SPRING_JPA_SHOW_SQL=false
before_install:
  - jdk_switcher use oraclejdk8
  - java -version
  - sudo /etc/init.d/mysql stop
  - sudo /etc/init.d/postgresql stop
  # Repo for Yarn
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH
  - sudo apt-get install sshpass -y
install:
  - yarn install
script:
  - chmod +x mvnw
  - echo $TRAVIS_COMMIT
  #- ./mvnw clean test
  #- yarn test
  #- ./mvnw verify -Pprod -DskipTests
notifications:
  webhooks:
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
after_success:
  - sshpass -p ${password} ssh -t ${username}@${server} "cd projects/AGILE-Manager && mkdir testdepuistravis"
