version: '2'
services:
    agilemanager-app:
        image: agilemanager
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://agilemanager-postgresql:5432/AgileManager
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    agilemanager-postgresql:
        extends:
            file: postgresql.yml
            service: agilemanager-postgresql
